########################
##### ABM LOGIN
########################

#------------------------------------
### ALTA DE USUARIO (post)
#------------------------------------
### USUARIO 1
POST http://localhost:3001/login/alta
content-type: application/json

{
    "usuario": "jperez",
    "pass": "123456"
}

#------------------------------------
### BAJA DE USUARIO (delete)
#------------------------------------
### USUARIO 1
DELETE http://localhost:3001/login/baja
content-type: application/json

{
    "usuario": "smariani",
    "pass": "Pa$$W0rd"
}

#------------------------------------
### CAMBIO DE PASS DE USUARIO (put)
#------------------------------------
### USUARIO 1
PUT http://localhost:3001/login/modificacion
content-type: application/json

{
    "usuario": "smariani",
    "pass": "12345",
    "newPass": "123456",
    "confNewPass": "123456"
}

#------------------------------------
### LOGIN DE USUARIO (post)
#------------------------------------
### USUARIO 1
POST http://localhost:3001/login
content-type: application/json

{
    "usuario": "smariani",
    "pass": "123456"
}

### USUARIO 2
POST http://localhost:3001/login
content-type: application/json

{
    "usuario": "jperez",
    "pass": "123456"
}

###############################################################
##### PRUEBAS ENTIDADES
###############################################################

#=================================================
########################
### Alumnos
########################
#------------------------------------
### CONSULTAR ALUMNOS (get)
#------------------------------------
GET http://localhost:3001/alu/nouser

###
GET http://localhost:3001/alu/jperez


#------------------------------------
### CONSULTAR ALUMNOS PAGINADO (get)
#------------------------------------
GET http://localhost:3001/alu/nouser/pag?Pagina=1&Registros=5

###
GET http://localhost:3001/alu/jperez/pag?Pagina=2&Registros=2


#------------------------------------
### CONSULTAR ALUMNO CON DNI (get)
#------------------------------------
GET http://localhost:3001/alu/nouser/25478958

###
GET http://localhost:3001/alu/jperez/25478958


#------------------------------------
### ALTA ALUMNO (post)
#------------------------------------
POST http://localhost:3001/alu/nouser/alta
content-type: application/json

{
    "nombre": "Lola",
    "apellido": "Mora",
    "dni": 98765432,
    "telefono": 41111111,
    "id_carrera": 3
}

###
POST  http://localhost:3001/alu/jperez/alta
content-type: application/json

{
    "nombre": "Lola",
    "apellido": "Mora",
    "dni": 98765430,
    "telefono": 41111111,
    "id_carrera": 3
}


#------------------------------------
### BAJA ALUMNO CON DNI (delete)
#------------------------------------
DELETE  http://localhost:3001/alu/nouser/baja/98765432

###
DELETE  http://localhost:3001/alu/jperez/baja/98765432


#------------------------------------
### MODIFICACION ALUMNO CON DNI(put)
#------------------------------------
PUT  http://localhost:3001/alu/nouser/modificacion/11111110
content-type: application/json

{
    "nombre": "Lola",
    "apellido": "Mora",
    "dni": 98765430,
    "telefono": 41111111,
    "id_carrera": 3
}

###
PUT  http://localhost:3001/alu/jperez/modificacion/98765430
content-type: application/json

{
    "nombre": "Lola",
    "apellido": "Mora",
    "dni": 98765439,
    "telefono": 41111111,
    "id_carrera": 3
}


#=================================================
########################
### Carreras
########################
#------------------------------------
### CONSULTAR CARRERAS (get)
#------------------------------------
GET http://localhost:3001/car/nouser

###
GET http://localhost:3001/car/jperez



#=================================================
########################
### Departamentos
########################
#------------------------------------
### CONSULTAR DEPARTAMENTOS (get)
#------------------------------------
GET http://localhost:3001/dep/nouser

###
GET http://localhost:3001/dep/jperez

#------------------------------------
### CONSULTAR DEPARTAMENTOS PAGINADO (get)
#------------------------------------
GET http://localhost:3001/dep/nouser/pag?Pagina=1&Registros=5

###
GET http://localhost:3001/dep/jperez/pag?Pagina=2&Registros=2

#------------------------------------
### ALTA DEPARTAMENTO (post)
#------------------------------------
POST http://localhost:3001/dep/nouser/alta
content-type: application/json

{
    "nombre": "Ingenieria",
    "cod_departamento": "ING123"
}

###
POST  http://localhost:3001/dep/jperez/alta
content-type: application/json

{
    "nombre": "Ingenieria",
    "cod_departamento": "ING123"
}

#------------------------------------
### BAJA DEPARTAMENTO CON COD_DEPARTAMENTO (delete)
#------------------------------------
DELETE  http://localhost:3001/dep/nouser/baja/ING123

###
DELETE  http://localhost:3001/dep/jperez/baja/ING123

#------------------------------------
### MODIFICACION DEPARTAMENTO CON COD_DEPARTAMENTO(put)
#------------------------------------
PUT  http://localhost:3001/dep/nouser/modificacion/ING123
content-type: application/json

{
    "nombre": "Ingenieria",
    "cod_departamento": "ING123"
}

###
PUT  http://localhost:3001/dep/jperez/modificacion/ING123
content-type: application/json

{
    "nombre": "IngenieriaS",
    "cod_departamento": "ING123S"
}

#=================================================
########################
### Materias
########################
#------------------------------------
### CONSULTAR MATERIAS (get)
#------------------------------------
GET http://localhost:3001/mat


#=================================================
########################
### Profesores
########################
#------------------------------------
### CONSULTAR PROFESORES (get)
#------------------------------------
GET http://localhost:3001/pro


#=================================================
########################
### Inscripciones
########################
#------------------------------------
### CONSULTAR INSCRIPCIONES (get)
#------------------------------------
GET http://localhost:3001/ins


#------------------------------------
### ALTA INSCRIPCION (post)
#------------------------------------
POST http://localhost:3001/ins/alta
content-type: application/json

{
    "dni": 47851246,
    "cod_materia": "ANA001"
}